### PR TITLE
Fix predict with collinear=true

### LINKED ISSUE #409: prediction on a linear model changed between version 1.3.11 and 1.4.0
In particular the reported confidence interval is different. On GLM v1.3.11 I get

```julia
julia> using GLM

julia> x = [1.0 1.0
            1.0 2.0
            1.0 -1.0];

julia> y = [1.0, 3.0, -2.0];

julia> m = lm(x, y);

julia> predict(m, x, interval=:confidence)
(prediction = [1.2142857142857142, 2.857142857142857, -2.0714285714285716], lower = [-0.8151383947225999; -0.012896241623634452; -5.343776620915804], upper = [3.2437098232940285; 5.727181955909349; 1.200919478058661])
```

whereas v1.4.0 gives

```julia
julia> using GLM

julia> x = [1.0 1.0
            1.0 2.0
            1.0 -1.0];

julia> y = [1.0, 3.0, -2.0];

julia> m = lm(x, y);

julia> predict(m, x, interval=:confidence)
(prediction = [1.2142857142857146, 2.8571428571428585, -2.0714285714285725], lower = [-0.8151383947225981; -1.0989330286373797; -5.343776620915804], upper = [3.2437098232940276; 6.813218742923096; 1.2009194780586587])
```

I don't think it is just a numerical instability, larger examples, eg

```julia
julia> x = hcat(fill(1, 100), 1:100);

julia> y = [i + 0.1 * isodd(i) for i in 1:100];
```

yield even larger differences.

### PR DESCRIPTION
**Pull request by nalimilan**
We need to reorder rows and columns when using pivoted Cholesky decomposition.

Fixes #409.

### CODE REVIEW

**Comment by nalimilan** [comment]
This doesn't seem to fix the case where there are collinear columns:
```julia
julia> x = [1.0 1.0 2.0
            1.0 2.0 3.0
            1.0 -1.0 0.0];

julia> y = [1.0, 3.0, -2.0];

julia> m1 = lm(x, y, dropcollinear=true)
LinearModel{GLM.LmResp{Array{Float64,1}},GLM.DensePredChol{Float64,CholeskyPivoted{Float64,Array{Float64,2}}}}:

Coefficients:
─────────────────────────────────────────────────────────────────
        Coef.  Std. Error       t  Pr(>|t|)  Lower 95%  Upper 95%
─────────────────────────────────────────────────────────────────
x1   0.0       NaN         NaN       NaN     NaN        NaN
x2   2.07143     0.257539    8.04    0.0787   -1.20092    5.34378
x3  -0.428571    0.174964   -2.45    0.2468   -2.65169    1.79455
─────────────────────────────────────────────────────────────────


julia> m2 = lm(x[:, 1:2], y, dropcollinear=false)
LinearModel{GLM.LmResp{Array{Float64,1}},GLM.DensePredChol{Float64,Cholesky{Float64,Array{Float64,2}}}}:

Coefficients:
────────────────────────────────────────────────────────────────
        Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────
x1  -0.428571    0.174964  -2.45    0.2468  -2.65169     1.79455
x2   1.64286     0.123718  13.28    0.0479   0.070872    3.21484
────────────────────────────────────────────────────────────────


julia> p1 = predict(m1, x, interval=:confidence);

julia> p2 = predict(m2, x[:, 1:2], interval=:confidence);

julia> @test p1.prediction ≈ p2.prediction
Test Passed

julia> @test p1.upper ≈ p2.upper
Test Failed at REPL[254]:1
  Expression: p1.upper ≈ p2.upper
   Evaluated: [3.354342064529162; 5.728437323463455; 1.6152034019232366] ≈ [3.2437098232940285; 5.727181955909349; 1.200919478058661]
ERROR: There was an error during testing

julia> @test p1.lower ≈ p2.lower
Test Failed at REPL[255]:1
  Expression: p1.lower ≈ p2.lower
   Evaluated: [-0.925770635957734; -0.014151609177741165; -5.758060544780381] ≈ [-0.8151383947225999; -0.012896241623634452; -5.343776620915804]
ERROR: There was an error during testing
```

In the worst case we could throw an error when calling `predict` in such cases until we have a fix.

(BTW I'm not sure why the intercept is dropped in this example rather than the last column.)

File: src/linpred.jl [hunk 1]
```diff
@@ -138,12 +138,12 @@ function delbeta!(p::DensePredChol{T,<:CholeskyPivoted}, r::Vector{T}) where T<:
     if rnk == length(delbeta)
         ldiv!(ch, delbeta)
     else
-        permute!(delbeta, ch.piv)
+        permute!(delbeta, ch.p)
```
Comment (ararslan) [inline src/linpred.jl:141]: I couldn't find documentation of the `p` property. Am I just being dense or is it undocumented?

Comment (nalimilan) [reply src/linpred.jl:141]: It's new. ;-) https://github.com/JuliaLang/julia/pull/39964

**Review by ararslan — APPROVED** [review]

**Comment by nalimilan** [comment]
Thanks! I've filed https://github.com/JuliaRegistries/General/pull/32024.
