### PR TITLE
Backtrack on non-finite deviance values

### LINKED ISSUE #417: Deviance NaN from first iteration onwards with Gamma distributed GLM with LogLink
I am trying to run a Gamma distributed GLM with a LogLink function, however, the deviance and diff.dev are both NaN from the first iteration. I have added the data files below (hopefully that's worked correctly - they are pretty small):

[x.txt](https://github.com/JuliaStats/GLM.jl/files/6279630/x.txt)
[y.txt](https://github.com/JuliaStats/GLM.jl/files/6279632/y.txt)

Reproducible example using data above:
```
using DelimitedFiles, GLM
X = readdlm("x.txt")
y = readdlm("y.txt")
y = reshape(y, 1000)  # Otherwise is a 1000 × 1 Matrix not a vector
glm(X, y, Gamma(), LogLink(), maxiter=5, verbose = true)
```

The output I get:
```
Iteration: 1, deviance: NaN, diff.dev.:NaN
Iteration: 2, deviance: NaN, diff.dev.:NaN
Iteration: 3, deviance: NaN, diff.dev.:NaN
Iteration: 4, deviance: NaN, diff.dev.:NaN
Iteration: 5, deviance: NaN, diff.dev.:NaN
```

Running this for any amount of iterations leads to the error:
```
failure to converge after 5 iterations.
_fit!(m::GeneralizedLinearModel{GLM.GlmResp{Vector{Float64}, Gamma{Float64}, LogLink}, GLM.DensePredChol{Float64, Cholesky{Float64, Matrix{Float64}}}}, verbose::Bool, maxiter::Int64, minstepfac::Float64, atol::Float64, rtol::Float64, start::Nothing) at glmfit.jl:339
#fit!#12 at glmfit.jl:372 [inlined]
fit! at glmfit.jl:352 [inlined]
fit(::Type{GeneralizedLinearModel}, X::Matrix{Float64}, y::Vector{Float64}, d::Gamma{Float64}, l::LogLink; dofit::Bool, wts::Vector{Float64}, offset::Vector{Float64}, fitargs::Base.Iterators.Pairs{Symbol, Integer, Tuple{Symbol, Symbol}, NamedTuple{(:maxiter, :verbose), Tuple{Int64, Bool}}}) at glmfit.jl:468
(::StatsBase.var"#fit##kw")(::NamedTuple{(:maxiter, :verbose), Tuple{Int64, Bool}}, ::typeof(fit), ::Type{GeneralizedLinearModel}, X::Matrix{Float64}, y::Vector{Float64}, d::Gamma{Float64}, l::LogLink) at glmfit.jl:462
glm(::Matrix{Float64}, ::Vector{Float64}, ::Gamma{Float64}, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Symbol, Integer, Tuple{Symbol, Symbol}, NamedTuple{(:maxiter, :verbose), Tuple{Int64, Bool}}}) at glmfit.jl:484
(::GLM.var"#glm##kw")(::NamedTuple{(:maxiter, :verbose), Tuple{Int64, Bool}}, ::typeof(glm), ::Matrix{Float64}, ::Vector{Float64}, ::Gamma{Float64}, ::Vararg{Any, N} where N) at glmfit.jl:484
top-level scope at sandbox.jl:229
eval at boot.jl:360 [inlined]

```

I will try and dig into this and narrow it down a bit further but I am not very familiar with GAMs, so any help would be much appreciated!

### PR DESCRIPTION
**Pull request by andreasnoack**
The current criterion for backtracking assumes that the deviance computed is finite. Hence, extreme parameter values can cause termination instead of reduction of the step.

Fixes #417

### CODE REVIEW

File: src/glmfit.jl [hunk 1]
```diff
@@ -402,7 +405,7 @@ function _fit!(m::AbstractGLM, verbose::Bool, maxiter::Integer, minstepfac::Real
         ## If the deviance isn't declining then half the step size
         ## The rtol*dev term is to avoid failure when deviance
         ## is unchanged except for rouding errors.
-        while dev > devold + rtol*dev
+        while !isfinite(dev) || dev > devold + rtol*dev
```
Comment (devmotion) [inline src/glmfit.jl:408]: It seems we could possibly end up in infinite loop here?

File: test/runtests.jl [hunk 2]
```diff
@@ -2032,4 +2032,15 @@ end
     f2 = lm(X, filip_data_df.y, dropcollinear = false, method = :qr, wts = ones(length(filip_data_df.y)))
     @test coef(f2) ≈ filip_estimates_df.estimate rtol = 1e-7
     @test stderror(f2) ≈ filip_estimates_df.se rtol = 1e-7
-end
\ No newline at end of file
+end
+
+@testset "Non-finite deviance. Issue 417" begin
+    X_fn = Downloads.download("https://gist.githubusercontent.com/andreasnoack/6068454679cbbc55e0f119ff0d16e92b/raw/de86ddbf66535558b1faedf00bdea59af9a86cb2/X.txt")
+    y_fn = Downloads.download("https://gist.githubusercontent.com/andreasnoack/6068454679cbbc55e0f119ff0d16e92b/raw/acdf8833760b4ea19d7167513ca967b9f7e87c21/y.txt")
```
Comment (devmotion) [inline test/runtests.jl:2039]: Are these the files included in the issue? You can directly link to them (I know Chris uses this trick sometimes when including e.g. plots in READMEs where he doesn't want the files to be added to the repo):
```suggestion
    X_fn = Downloads.download("https://github.com/JuliaStats/GLM.jl/files/6279630/x.txt")
    y_fn = Downloads.download("https://github.com/JuliaStats/GLM.jl/files/6279632/y.txt")
```

File: src/glmfit.jl (hunk 1 above)
Comment (andreasnoack) [reply src/glmfit.jl:408]: Doesn't line 410 guard against that?
